server:
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  name: wrale_test
  user: postgres
  password: postgres
  
redis:
  host: localhost
  port: 6379

ratelimit:
  settings:
    max_wait_time: 2s
  api: 
    requests_per_minute: 120
    burst_size: 30
    device_code_per_interval: 10  # Increased from 3
    device_code_interval: 1m      # Reduced from 5m
    token_refresh_per_hour: 10 
    refresh_burst_size: 3
  websocket:
    messages_per_minute: 60
    burst_size: 15

auth:
  access_token_expiry: 1h
  refresh_token_expiry: 90d
  issuer: "wrale-signage-dev"
